//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopV2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public Nullable<int> IdProductName { get; set; }
        public Nullable<int> IdManufacture { get; set; }
        public Nullable<int> IdSupplier { get; set; }
        public string ProductArticleNumber { get; set; }
        public Nullable<decimal> ProductCost { get; set; }
        public string ProductDiscountAmount { get; set; }
        public string DiscountNow { get; set; }
        public Nullable<int> ProductQuantityInStock { get; set; }
        public string ProductDesription { get; set; }
        public string PhotoName { get; set; }
        public byte[] ProductPhoto { get; set; }
        public Nullable<int> IdUnits { get; set; }
        public Nullable<int> IdCategory { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        public virtual ProductName ProductName { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Units Units { get; set; }
    }
}
